import NotesMap from "../Note/NotesMap";
import EqualTemperament from "./Equal";

export type Temperament = {
  idTemperament: number,
  name: string,
  nameFR: string,
  deviation: NotesMap<number>,
  cpExp5th: NotesMap<string>,
  csExp5th: NotesMap<string>
  csExp3rd: NotesMap<string>,
  procedure: string,
  period : string,
  theorist : string,
  geographicalArea: string,
  nature: string,
  structuralParticularity: string,
  wikipedia: Array<{name: string, url: string}>,
  sources: Array<{author: string, book: string, title:string, other: string, date: string, page: string, url:string}>,
  references: Array<{author: string, book: string, title:string, other: string, date: string, page: string, url:string}>,
  soundReferences: Array<string>,
  commentary: string,
  externalLinks: Array<{name: string, url: string}>,
};

export const defaultTemperaments: Array<Temperament> = [
  EqualTemperament,
  {
    idTemperament: 2,
    name: "Vallotti",
    nameFR: "Vallotti",
    deviation: {
      C:        5.865,
      C_sharp:  0.000,
      D:        1.955,
      E_flat:   3.910,
      E:       -1.955,
      F:        7.820,
      F_sharp: -1.955,
      G:        3.910,
      G_sharp:  1.955,
      A:        0.000,
      B_flat:   5.865,
      B:       -3.910,
    },
    cpExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "-1/6",
      C:       "-1/6",
      G:       "-1/6",
      D:       "-1/6",
      A:       "-1/6",
      E:       "-1/6",
      B:       "0",
    },
    csExp3rd: {
      F_sharp: "+11/11",
      C_sharp: "+11/11",
      G_sharp: "+9/11",
      E_flat:  "+7/11",
      B_flat:  "+5/11",
      F:       "+3/11",
      C:       "+3/11",
      G:       "+3/11",
      D:       "+5/11",
      A:       "+7/11",
      E:       "+9/11",
      B:       "+11/11",
    },
    procedure: "A4;A4-A3;A3-F3;F3-Bb3;Bb3-Eb4;Eb4-G#3;G#3-C#4;C#4:A3;C#4-F#3;F#3-B3;B3-E4;E4:A3;A3-D4;D4-G3;G3-C4;C4:F3;F#3-F#4;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "-1/5,5",
      C:       "-1/5,5",
      G:       "-1/5,5",
      D:       "-1/5,5",
      A:       "-1/5,5",
      E:       "-1/5,5",
      B:       "0",
    },
    externalLinks:[{name: "Wikipedia Temperament Mésotonique (FR)", url: "https://fr.wikipedia.org/wiki/Temp%C3%A9rament_m%C3%A9sotonique"},],
    theorist : "Pietro Aaron (1485-1545)",
    wikipedia: [
      {name: "Wikipedia Pietro Aaron (FR) ", url: "https://fr.wikipedia.org/wiki/Pietro_Aaron"},],
    period : "décrit au début du XVIe siècle, on présume une utilisation dès le XVe siècle. Son application est avérée sur l'orgue pendant la première moitié du XVIIIe siècle.",
    geographicalArea: "plusieurs sources importantes en dehors de l'Italie (Praetorius, Mersenne) laissent à penser que cet accord est très tôt utilisé dans toute l'Europe.",
    nature: "Comma syntonique",
    structuralParticularity: "11 quintes sont diminuées d'un quart de comma syntonique. La douzième, l'intervalle résiduel entre sol# et mib, excède la valeur pure. Le système mésotonique classique produit huit tierces majeures pures. Chaque octave comporte 2 tierces pures et un intervalle résiduel (une quarte diminuée), excédant d’un comma enharmonique (2 ÷ (5/4)^3 = 41,05¢).",
    sources: [
      {author: "Pietro Aaron", book: "Toscanello de la musica", title:"", other: ", Venise", date: "1523", page: "", url:""}
    ],
    references: [{author: "Barbieri, Patrizio,", book: "Acustica accordatura e temperamento nell'illuminismo veneto. Insituto di Paleografia Musicale,", title:"", other: "Torre d'Orfeo, Roma", date: "1987", page: "", url:""}],
    soundReferences: ["https://www.youtube.com/watch?v=TDCpdNOJC5s","https://www.youtube.com/watch?v=hw1O5t_Rrhg"],
    commentary: "Nous proposons la lecture la plus partagée bien que certainement simplifiée de l'accord de Vallotti qui répartit lui-même le comma syntonique, selon la théorie italienne du XVIIIe siècle. L'accroissement des tierces majeures est parfaitement équilibré vers les dièses et vers les bémols.",
  },{
    idTemperament: 3,
    name: "Meantone 1/4 G#Eb",
    nameFR: "Mésotonique",
    deviation: {
      C:        10.263,
      C_sharp: -13.686,
      D:         3.420,
      E_flat:   20.528,
      E:        -3.422,
      F:        13.685,
      F_sharp: -10.265,
      G:         6.842,
      G_sharp: -17.108,
      A:         0.000,
      B_flat:   17.106,
      B:        -6.843,
    },
    cpExp5th: {
      F_sharp: "-1/4.36",
      C_sharp: "-1/4.36",
      G_sharp: "+1/0.66",
      E_flat:  "-1/4.36",
      B_flat:  "-1/4.36",
      F:       "-1/4.36",
      C:       "-1/4.36",
      G:       "-1/4.36",
      D:       "-1/4.36",
      A:       "-1/4.36",
      E:       "-1/4.36",
      B:       "-1/4.36",
    },
    csExp3rd: {
      F_sharp: "21/11",
      C_sharp: "21/11",
      G_sharp: "21/11",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "0",
      G:       "0",
      D:       "0",
      A:       "0",
      E:       "0",
      B:       "21/11",
    },
    procedure : "A4;A4-A3;A3-F3;F3-F4;A3-C#4;C#4:F4;{on divise la tierce F-A en quatre quintes tempérées à -¼ de comma}F3-C4;C4-G3;G3-G4;G3-D4;A3:D4;C4-E4;E4:A3;E4-G#4;G#4-G#3;G#3:C3;G3-B3;B3:E4;B3-Eb4;Eb4:G4;D4-F#4;F#4-F#3;F#3-Bb3;Bb3:D4",
    csExp5th: {
      F_sharp: "-1/4",
      C_sharp: "-1/4",
      G_sharp: "+1/0,6",
      E_flat:  "-1/4",
      B_flat:  "-1/4",
      F:       "-1/4",
      C:       "-1/4",
      G:       "-1/4",
      D:       "-1/4",
      A:       "-1/4",
      E:       "-1/4",
      B:       "-1/4",
    },
    externalLinks:[{name: "Wikipedia Temperament de Vallotti (FR)", url: "https://fr.wikipedia.org/wiki/Temp%C3%A9rament_de_Vallotti"},],
    theorist : "Francesco Vallotti (1697-1780)",
    wikipedia: [
      {name: "Wikipedia Francesco Vallotti (FR) ", url: "https://fr.wikipedia.org/wiki/Francesco_Antonio_Vallotti"},
      {name: "Wikipedia Francesco Vallotti (EN) ", url: "https://en.wikipedia.org/wiki/Francesco_Antonio_Vallotti"}],
    period : "XVIIIe siècle",
    geographicalArea: "Italie du Nord",
    nature: "1/6 de comma pythagoricien",
    structuralParticularity: "Six quintes tempérées au 1/6 de comma pythagoricien relient les notes naturelles, les six autres sont pures.",
    sources: [
      {author: "Francesco Antonio Vallotti", book: "Trattato della musica moderna", title:"", other: "inédit du temps de Vallotti. Zanini", date: "1950", page: "", url:""}
    ],
    references: [
      {author: "Barbieri, Patrizio,", book: "Acustica accordatura e temperamento nell'illuminismo veneto. Insituto di Paleografia Musicale,", title:"", other: "Torre d'Orfeo, Roma", date: "1987", page: ", p. 37-51", url:""},
      {author: "", book: "", title:"Thoscanello de la musica", other: "", date: "", page: "", url:"https://imslp.org/wiki/Thoscanello_de_la_musica_(Aron,_Pietro)"}],
      soundReferences: [
        "https://www.youtube.com/watch?v=KHlne0rAnTg",
        "http://blog-clavicorde-lie.ch/laccord-mesotonique-realise-sur-linstrument/",
        "https://www.youtube.com/watch?v=jcAIh1V2Zz8",
        "https://www.youtube.com/watch?v=e83oOCnH_3w",],
    commentary: "",
  },
  {
    idTemperament: 4,
    name: "Rameau 1726 (b)",
    nameFR: "Rameau 1726 (b)",
    deviation: {
      C:       10.265,
      C_sharp:  0.578,
      D:        3.422,
      E_flat:  13.375,
      E:       -3.422,
      F:       13.686,
      F_sharp: -8.487,
      G:        6.843,
      G_sharp:  7.865,
      A:        0.000,
      B_flat:  17.108,
      B:       -6.843,
    },
    cpExp5th: {
      F_sharp: "+1/3.3",
      C_sharp: "+1/4.4",
      G_sharp: "+1/6.6",
      E_flat:  "+1/13.19",
      B_flat:  "-1/4.36",
      F:       "-1/4.36",
      C:       "-1/4.36",
      G:       "-1/4.36",
      D:       "-1/4.36",
      A:       "-1/4.36",
      E:       "-1/4.36",
      B:       "-1/6.52",
    },
    csExp3rd: {
      F_sharp: "20/11",
      C_sharp: "14/11",
      G_sharp: "8/11",
      E_flat:  "4/11",
      B_flat:  "0",
      F:       "0",
      C:       "0",
      G:       "0",
      D:       "1/11",
      A:       "7/11",
      E:       "13/11",
      B:       "17/11",
    },
    procedure: "A4;A4-A3;A3-F3;F3-C4;C4-G3;G3-D4;D4:A3;D4-Bb3;C4-E4;G3-B3;Bb3-Eb4;Eb4-G#3;G#3-C#4;B3-F#3;F3-F4;F#3-F#4;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "+1/3,02",
      C_sharp: "+1/4,03",
      G_sharp: "+1/6,05",
      E_flat:  "+1/12,1",
      B_flat:  "-1/4",
      F:       "-1/4",
      C:       "-1/4",
      G:       "-1/4",
      D:       "-1/4",
      A:       "-1/4",
      E:       "-1/4",
      B:       "-1/5,98",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
      soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 5,
    name: "Rameau 1726 (#)",
    nameFR: "Rameau 1726 (#)",
    deviation: {
      C:        10.265,
      C_sharp: -13.686,
      D:         3.422,
      E_flat:   -6.265,
      E:        -3.422,
      F:         6.532,
      F_sharp: -10.265,
      G:         6.843,
      G_sharp: -15.330,
      A:         0.000,
      B_flat:    1.022,
      B:        -6.843,
    },
    cpExp5th: {
      F_sharp: "-1/4.36",
      C_sharp: "-1/6.52",
      G_sharp: "+1/3.3",
      E_flat:  "+1/4.4",
      B_flat:  "+1/6.6",
      F:       "+1/13.19",
      C:       "-1/4.36",
      G:       "-1/4.36",
      D:       "-1/4.36",
      A:       "-1/4.36",
      E:       "-1/4.36",
      B:       "-1/4.36",
    },
    csExp3rd: {
      F_sharp: "13/11",
      C_sharp: "17/11",
      G_sharp: "20/11",
      E_flat:  "14/11",
      B_flat:  "8/11",
      F:       "4/11",
      C:       "0",
      G:       "0",
      D:       "0",
      A:       "0",
      E:       "1/11",
      B:       "7/11",
    },
    procedure: "A4;A4-A3;A3-C#;A3-E4;E4-B3;B3-F#3;F#3-C#4;F#3-F#4;F#4-D4;B3-G3;E4-C4;A3-F3;F3:C4;F3-Bb3;Bb3-Eb4;C#4-G#3;G#3:Eb4;F3-F4;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "-1/4",
      C_sharp: "-1/5,98",
      G_sharp: "+1/3,02",
      E_flat:  "+1/4,03",
      B_flat:  "+1/6,05",
      F:       "+1/12,1",
      C:       "-1/4",
      G:       "-1/4",
      D:       "-1/4",
      A:       "-1/4",
      E:       "-1/4",
      B:       "-1/4",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
      soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 6,
    name: "Bach/Kellner",
    nameFR: "Bach/Kellner",
    deviation: {
      C:        8.211,
      C_sharp: -1.564,
      D:        2.737,
      E_flat:   2.346,
      E:       -2.737,
      F:        6.256,
      F_sharp: -3.519,
      G:        5.474,
      G_sharp:  0.391,
      A:        0.000,
      B_flat:   4.301,
      B:       -0.782,
    },
    cpExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "-1/5",
      G:       "-1/5",
      D:       "-1/5",
      A:       "-1/5",
      E:       "0",
      B:       "-1/5",
    },
    csExp3rd: {
      F_sharp: "11/11",
      C_sharp: "11/11",
      G_sharp: "11/11",
      E_flat:  "9/11",
      B_flat:  "6/11",
      F:       "4/11",
      C:       "1/11",
      G:       "4/11",
      D:       "4/11",
      A:       "6/11",
      E:       "9/11",
      B:       "9/11",
    },
    procedure: "A4;A4-A3;A3-F3;F3-C4;C4-E4;E4:A3;C4-G3;G3-D4;D4:A3;F3-Bb3;Bb3-Eb4;Eb4-G#3;G#3-C#4;C#4-F#3;E4-B3;B3:F#3;F3-F4;F#3-F#4;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "-1/4,58",
      G:       "-1/4,58",
      D:       "-1/4,58",
      A:       "-1/4,58",
      E:       "0",
      B:       "-1/4,58",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
    soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 7,
    name: "Werckmeister I(III)",
    nameFR: "Werckmeister I(III)",
    deviation: {
      C:       11.730,
      C_sharp:  1.955,
      D:        3.910,
      E_flat:   5.865,
      E:        1.955,
      F:        9.775,
      F_sharp:  0.000,
      G:        7.820,
      G_sharp:  3.910,
      A:        0.000,
      B_flat:   7.820,
      B:        3.910,
    },
    cpExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "-1/4",
      G:       "-1/4",
      D:       "-1/4",
      A:       "0",
      E:       "0",
      B:       "-1/4",
    },
    csExp3rd: {
      F_sharp: "11/11",
      C_sharp: "11/11",
      G_sharp: "11/11",
      E_flat:  "8/11",
      B_flat:  "5/11",
      F:       "2/11",
      C:       "2/11",
      G:       "5/11",
      D:       "5/11",
      A:       "8/11",
      E:       "8/11",
      B:       "8/11",
    },
    procedure: "A4;A4-A3;A3-E4;E4-B3;B3-F#4;F#4-C#4;A3:C#4;C#4-G#4;G#4-D#4;D#4-Bb3;Bb3-F4;F4-F3;F3:A3;F4-C4;C4:E4;C4-G4;G4-D4;D4:A4;F4-F3;F#4-F#3",
    csExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "-1/3,67",
      G:       "-1/3,67",
      D:       "-1/3,67",
      A:       "0",
      E:       "0",
      B:       "-1/3,67",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
    soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 8,
    name: "Werckmeister III(V)",
    nameFR: "Werckmeister III(V)",
    deviation: {
      C:        0.000,
      C_sharp: -3.910,
      D:        3.910,
      E_flat:   0.000,
      E:       -3.910,
      F:        3.910,
      F_sharp:  0.000,
      G:        1.955,
      G_sharp: -7.820,
      A:        0.000,
      B_flat:   1.955,
      B:       -1.955,
    },
    cpExp5th: {
      F_sharp: "-1/4",
      C_sharp: "-1/4",
      G_sharp: "+1/4",
      E_flat:  "0",
      B_flat:  "0",
      F:       "-1/4",
      C:       "0",
      G:       "0",
      D:       "-1/4",
      A:       "-1/4",
      E:       "0",
      B:       "0",
    },
    csExp3rd: {
      F_sharp: "8/11",
      C_sharp: "11/11",
      G_sharp: "11/11",
      E_flat:  "8/11",
      B_flat:  "8/11",
      F:       "5/11",
      C:       "5/11",
      G:       "5/11",
      D:       "5/11",
      A:       "5/11",
      E:       "5/11",
      B:       "8/11",
    },
    procedure: "A4;A4-A3;A3-F3;F3-Bb3;Bb3-Eb4;Eb4-Eb3;Eb3-G3;F3-C4;C4:G3;G3-D4;D4:A3;A3-E4;E4:C3;E4-E3;E3-B3;G3:B3;B3-F#3;F#3-C#4;C#4:A3;C#4-G#3;G#3:Eb4;F3-F4;F#3-F#4;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "-1/3,67",
      C_sharp: "-1/3,67",
      G_sharp: "+1/3,67",
      E_flat:  "0",
      B_flat:  "0",
      F:       "-1/3,67",
      C:       "0",
      G:       "0",
      D:       "-1/3,67",
      A:       "-1/3,67",
      E:       "0",
      B:       "0",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
    soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 9,
    name: "Pythagorean G#Eb",
    nameFR: "Pythagoricien G#Eb",
    deviation: {
      C:        -5.865,
      C_sharp:   7.820,
      D:        -1.955,
      E_flat:  -11.730,
      E:         1.955,
      F:        -7.820,
      F_sharp:   5.865,
      G:        -3.910,
      G_sharp:   9.775,
      A:         0.000,
      B_flat:   -9.775,
      B:         3.910,
    },
    cpExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "-1/1",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "0",
      G:       "0",
      D:       "0",
      A:       "0",
      E:       "0",
      B:       "0",
    },
    csExp3rd: {
      F_sharp: "-1/11",
      C_sharp: "-1/11",
      G_sharp: "-1/11",
      E_flat:  "11/11",
      B_flat:  "11/11",
      F:       "11/11",
      C:       "11/11",
      G:       "11/11",
      D:       "11/11",
      A:       "11/11",
      E:       "11/11",
      B:       "-1/11",
    },
    procedure: "",
    csExp5th: {
      F_sharp: "0",
      C_sharp: "0",
      G_sharp: "-1/0,92",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "0",
      G:       "0",
      D:       "0",
      A:       "0",
      E:       "0",
      B:       "0",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
    soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 10,
    name: "Kirnberger III (1779)",
    nameFR: "Kirnberger III (1779)",
    deviation: {
      C:       10.264,
      C_sharp:  0.489,
      D:        3.421,
      E_flat:   4.399,
      E:       -3.422,
      F:        8.309,
      F_sharp:  0.488,
      G:        6.842,
      G_sharp:  2.444,
      A:        0.000,
      B_flat:   6.354,
      B:       -1.467,
    },
    cpExp5th: {
      F_sharp: "-1/12.01",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "-1/4.36",
      G:       "-1/4.36",
      D:       "-1/4.36",
      A:       "-1/4.36",
      E:       "0",
      B:       "0",
    },
    csExp3rd: {
      F_sharp: "10/11",
      C_sharp: "11/11",
      G_sharp: "11/11",
      E_flat:  "8/11",
      B_flat:  "5/11",
      F:       "3/11",
      C:       "0",
      G:       "3/11",
      D:       "5/11",
      A:       "7/11",
      E:       "10/11",
      B:       "10/11",
    },
    procedure: "A4;A4-A3;A3-F3;F3-C4;C4-E4;E4:A3;C4-G3;G3-D4;D4:A3;F3-Bb3;Bb3-Eb4;Eb4-G#3;G#3-C#4;E4-B3;B3-F#3;F#3:C#4;F3-F4;F#3-F#4;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "-1/11,01",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "0",
      B_flat:  "0",
      F:       "0",
      C:       "-1/4",
      G:       "-1/4",
      D:       "-1/4",
      A:       "-1/4",
      E:       "0",
      B:       "0",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
    soundReferences: [
        "",],
    commentary: "",
  },
  {
    idTemperament: 11,
    name: "Bertier 'elliptical'",
    nameFR: "Bertier 'elliptique'",
    deviation: {
      C:        5.341,
      C_sharp:  0.000,
      D:        1.955,
      E_flat:   3.910,
      E:       -1.431,
      F:        5.865,
      F_sharp: -1.431,
      G:        3.910,
      G_sharp:  1.955,
      A:        0.000,
      B_flat:   5.341,
      B:       -1.955,
    },
    cpExp5th: {
      F_sharp: "-1/44.77",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "-1/44.77",
      B_flat:  "-1/16.39",
      F:       "-1/9.46",
      C:       "-1/6.93",
      G:       "-1/6",
      D:       "-1/6",
      A:       "-1/6.93",
      E:       "-1/9.46",
      B:       "-1/16.39",
    },
    csExp3rd: {
      F_sharp: "10/11",
      C_sharp: "10/11",
      G_sharp: "9/11",
      E_flat:  "7/11",
      B_flat:  "5/11",
      F:       "4/11",
      C:       "4/11",
      G:       "4/11",
      D:       "5/11",
      A:       "7/11",
      E:       "9/11",
      B:       "10/11",
    },
    procedure: "A4;A4-F3;F3-C4;C4-G3;G3-D4;D4:A3;A3-E4;E4:C4;E4-B3;B3:G3;B3-F#4;F#4:D3;F3-Bb3;Bb3:D4;Bb3-Eb4;Eb4-G#3;G#3-C#4;C#4:A3;C#4:F4;F4-F3;G3-G4;G#3-G#4",
    csExp5th: {
      F_sharp: "-1/41,03",
      C_sharp: "0",
      G_sharp: "0",
      E_flat:  "-1/41,03",
      B_flat:  "-1/15,03",
      F:       "-1/8,67",
      C:       "-1/6,35",
      G:       "-1/5,5",
      D:       "-1/5,5",
      A:       "-1/6,35",
      E:       "-1/8,67",
      B:       "-1/15,03",
    },
    externalLinks:[
      {name: "", url: ""},
    ],
    theorist : "",
    wikipedia: [
      {name: "", url: ""},
      {name: "", url: ""},
    ],
    period : "",
    geographicalArea: "",
    nature: "",
    structuralParticularity: "",
    sources: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url:""}
    ],
    references: [
      {author: "", book: "", title:"", other: "", date: "", page: "", url: ""},
    ],
    soundReferences: [
        "",],
    commentary: "",
  },
];
