language: node_js
node_js:
  - "14.18.0"
script:
  - npm install -g firebase-tools
  - npm install -g @ionic/cli
  - npm install
  - ionic build --prod 
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"